---
dependency:
  name: galaxy
lint: |
  set -e
  yamllint .
  ansible-lint
driver:
  name: docker
platforms:
  - name: ns1.homelab.example.com
    image: "ricsanfre/docker-${MOLECULE_DISTRO:-ubuntu}-ansible:${MOLECULE_RELEASE:-latest}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    privileged: true
    pre_build_image: true
    docker_networks:
      - name: molecule
        ipam_config:
          - subnet: "10.11.0.0/16"
            gateway: "10.11.0.254"
    networks:
      - name: molecule
        ipv4_address: "10.11.0.11"
  - name: ns2.homelab.example.com
    image: "ricsanfre/docker-${MOLECULE_DISTRO:-ubuntu}-ansible:${MOLECULE_RELEASE:-latest}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    privileged: true
    pre_build_image: true
    networks:
      - name: molecule
        ipv4_address: "10.11.0.12"
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  inventory:
    host_vars:
      localhost:
        ansible_user: ${USER}
verifier:
  name: ansible
